import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations'

@table(process.env.dictionaryTableName)
export default class DictionaryModel {
  @autoGeneratedHashKey()
  id

  @attribute({type: 'String'})
  slug

  @attribute({type: 'String'})
  name

  @attribute({type: 'Boolean'})
  isFlat

  @attribute({type: 'Boolean'})
  isOpen
}
