import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations'

@table(process.env.termTableName)
export default class TermModel {
  @autoGeneratedHashKey()
  id

  @attribute({type: 'String'})
  dictionaryId

  @attribute({type: 'String'})
  parent

  @attribute({type: 'String'})
  term

  @attribute({type: 'String'})
  fullTerm

  @attribute({type: 'Set', memberType: 'String'})
  synonyms

  @attribute({type: 'Set', memberType: 'String'})
  childrens
}
