# term-get:
#   handler: ${self:custom.path.term}/get.default
#   events:
#     - http:
#         path: term/{id}
#         method: get
#         cors: true
term-get-all:
  handler: ${self:custom.path.term}/getAll.default
  events:
    - http:
        path: term
        method: get
        cors: true
term-put:
  handler: ${self:custom.path.term}/put.default
  events:
    - http:
        path: term
        method: post
        cors: true
        authorizer: aws_iam
# term-update:
#   handler: ${self:custom.path.term}/update.default
#   events:
#     - http:
#         path: term/{id}
#         method: put
#         cors: true
#         authorizer: aws_iam
# term-delete:
#   handler: ${self:custom.path.term}/delete.default
#   events:
#     - http:
#         path: term/{id}
#         method: delete
#         cors: true
#         authorizer: aws_iam
