Resources:
  DictionaryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dictionaryTable.name}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.dictionaryTable.throughput}
        WriteCapacityUnits: ${self:custom.dictionaryTable.throughput}
  TermsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.termsTable.name}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.termsTable.throughput}
        WriteCapacityUnits: ${self:custom.termsTable.throughput}
