term-find-all-by-dictionary:
  handler: ${self:custom.path.term}/findAllByDictionary.default
  events:
    - http:
        path: termFindAllByDictionary/{dictionaryId}/{term}
        method: get
        cors: true
term-find-all:
  handler: ${self:custom.path.term}/findAll.default
  events:
    - http:
        path: termFindAll/{term}
        method: get
        cors: true
term-get-all-by-parent:
  handler: ${self:custom.path.term}/getAllByParent.default
  events:
    - http:
        path: termAllByParent/{parent}
        method: get
        cors: true
term-get-by-id:
  handler: ${self:custom.path.term}/getById.default
  events:
    - http:
        path: term/{id}
        method: get
        cors: true
term-get-by-full-term:
  handler: ${self:custom.path.term}/getByFullTerm.default
  events:
    - http:
        path: termByFullTerm/{fullTerm}
        method: get
        cors: true
term-put:
  handler: ${self:custom.path.term}/put.default
  events:
    - http:
        path: term
        method: post
        cors: true
        authorizer: aws_iam
term-put-all:
  handler: ${self:custom.path.term}/putAll.default
  events:
    - http:
        path: termAll
        method: post
        cors: true
        authorizer: aws_iam
# term-update:
#   handler: ${self:custom.path.term}/update.default
#   events:
#     - http:
#         path: term/{id}
#         method: put
#         cors: true
#         authorizer: aws_iam
# term-delete:
#   handler: ${self:custom.path.term}/delete.default
#   events:
#     - http:
#         path: term/{id}
#         method: delete
#         cors: true
#         authorizer: aws_iam
